package db;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import org.json.JSONObject;

import javax.persistence.*;
import java.util.Date;

/**
 * Paper generated by hbm2java
 */
@Entity
@Table(name = "PAPER")
public class Paper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8783428717971245116L;
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Integer idpaper;
	private String papername;
	private Date paperdate;
	private Integer isactive;

	public Paper() {
	}

	public Paper(String papername, Date paperdate, Integer isactive) {
		this.papername = papername;
		this.paperdate = paperdate;
		this.isactive = isactive;
	}

	public Integer getIdpaper() {
		return this.idpaper;
	}

	public void setIdpaper(Integer idpaper) {
		this.idpaper = idpaper;
	}

	public String getPapername() {
		return this.papername;
	}

	public void setPapername(String papername) {
		this.papername = papername;
	}

	public Date getPaperdate() {
		return this.paperdate;
	}

	public void setPaperdate(Date paperdate) {
		this.paperdate = paperdate;
	}

	public Integer getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Integer isactive) {
		this.isactive = isactive;
	}

	@Override
	public String toString() {
		JSONObject jsonObject = new JSONObject();
		jsonObject.put("idpaper", idpaper);
		jsonObject.put("papername", papername);
		jsonObject.put("isactive", isactive);
		return jsonObject.toString();
	}
}
