package db;

import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private Integer idmodule;
	private String modulename;
	private Set problems = new HashSet(0);

	public Module() {
	}

	public Module(String modulename, Set problems) {
		this.modulename = modulename;
		this.problems = problems;
	}

	public Integer getIdmodule() {
		return this.idmodule;
	}

	public void setIdmodule(Integer idmodule) {
		this.idmodule = idmodule;
	}

	public String getModulename() {
		return this.modulename;
	}

	public void setModulename(String modulename) {
		this.modulename = modulename;
	}

	public Set getProblems() {
		return this.problems;
	}

	public void setProblems(Set problems) {
		this.problems = problems;
	}

}
