package db;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Problem generated by hbm2java
 */
public class Problem implements java.io.Serializable {
	
	public enum ProblemColumnName { idproblem, sourcechapter, 
		problemlevel,problemdetail,problemindex ,problemcisactive,
		problemanswerstring,problemanswerdetail,problemmodule,problemchapterid};

	private Integer idproblem;
	private Module module;
	private Integer problemchapterid;
	public Integer getProblemchapterid() {
		return problemchapterid;
	}

	public void setProblemchapterid(Integer problemchapterid) {
		this.problemchapterid = problemchapterid;
	}

	private Integer problemmodule;
	public Integer getProblemmodule() {
		return problemmodule;
	}

	public void setProblemmodule(Integer problemmodule) {
		this.problemmodule = problemmodule;
	}

	private SourceChapter sourcechapter;
	private Integer problemlevel;
	private String problemdetail;
	private String problemindex;
	private Integer problemcisactive;
	private String problemanswerstring;
	private String problemanswerdetail;
	private Set works = new HashSet(0);

	public Problem() {
		problemcisactive = 0;
	}

	public Problem(Module module, SourceChapter sourcechapter, Integer problemlevel, String problemdetail,
			String problemindex, Integer problemcisactive, String problemanswerstring, String problemanswerdetail,
			Set works) {
		this.module = module;
		this.sourcechapter = sourcechapter;
		this.problemlevel = problemlevel;
		this.problemdetail = problemdetail;
		this.problemindex = problemindex;
		this.problemcisactive = problemcisactive;
		this.problemanswerstring = problemanswerstring;
		this.problemanswerdetail = problemanswerdetail;
		this.works = works;
	}

	public Integer getIdproblem() {
		return this.idproblem;
	}

	public void setIdproblem(Integer idproblem) {
		this.idproblem = idproblem;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public SourceChapter getSourcechapter() {
		return this.sourcechapter;
	}

	public void setSourcechapter(SourceChapter sourcechapter) {
		this.sourcechapter = sourcechapter;
	}

	public Integer getProblemlevel() {
		return this.problemlevel;
	}

	public void setProblemlevel(Integer problemlevel) {
		this.problemlevel = problemlevel;
	}

	public String getProblemdetail() {
		return this.problemdetail;
	}

	public void setProblemdetail(String problemdetail) {
		this.problemdetail = problemdetail;
	}

	public String getProblemindex() {
		return this.problemindex;
	}

	public void setProblemindex(String problemindex) {
		this.problemindex = problemindex;
	}

	public Integer getProblemcisactive() {
		return this.problemcisactive;
	}

	public void setProblemcisactive(Integer problemcisactive) {
		this.problemcisactive = problemcisactive;
	}

	public String getProblemanswerstring() {
		return this.problemanswerstring;
	}

	public void setProblemanswerstring(String problemanswerstring) {
		this.problemanswerstring = problemanswerstring;
	}

	public String getProblemanswerdetail() {
		return this.problemanswerdetail;
	}

	public void setProblemanswerdetail(String problemanswerdetail) {
		this.problemanswerdetail = problemanswerdetail;
	}

	public Set getWorks() {
		return this.works;
	}

	public void setWorks(Set works) {
		this.works = works;
	}
	
	

}
