package dbmodel;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module")
public class Module implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2692219131681932676L;
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private Integer idmodule;
	private String modulename;

	public Module() {
	}

	public Integer getIdmodule() {
		return this.idmodule;
	}

	public void setIdmodule(Integer idmodule) {
		this.idmodule = idmodule;
	}

	public String getModulename() {
		return this.modulename;
	}

	public void setModulename(String modulename) {
		this.modulename = modulename;
	}

}
