package dbmodel;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.*;

/**
 * Problem generated by hbm2java
 */
@Entity
@Table(name = "problem")
public class Problem implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7257495385290311167L;

	public enum ProblemColumnName { idproblem, sourcechapter, 
		problemlevel,problemdetail,problemdetailb, problemdetailc, problemindex ,problemcisactive,
		problemanswerstring,problemanswerdetail,problemmodule,problemchapterid};

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Integer idproblem;
	private Integer problemchapterid;
	public Integer getProblemchapterid() {
		return problemchapterid;
	}

	public void setProblemchapterid(Integer problemchapterid) {
		this.problemchapterid = problemchapterid;
	}

	private Integer problemmodule;
	public Integer getProblemmodule() {
		return problemmodule;
	}

	public void setProblemmodule(Integer problemmodule) {
		this.problemmodule = problemmodule;
	}

	private Integer problemlevel;
	private String problemdetail;

	public String getProblemdetailb() {
		return problemdetailb;
	}

	public void setProblemdetailb(String problemdetailb) {
		this.problemdetailb = problemdetailb;
	}

	public String getProblemdetailc() {
		return problemdetailc;
	}

	public void setProblemdetailc(String problemdetailc) {
		this.problemdetailc = problemdetailc;
	}

	private String problemdetailb;
	private String problemdetailc;
	private String problemindex;
	private Integer problemcisactive;
	private String problemanswerstring;
	private String problemanswerdetail;

	public Problem() {
		problemcisactive = 0;
	}

	public Integer getIdproblem() {
		return this.idproblem;
	}

	public void setIdproblem(Integer idproblem) {
		this.idproblem = idproblem;
	}

	public Integer getProblemlevel() {
		return this.problemlevel;
	}

	public void setProblemlevel(Integer problemlevel) {
		this.problemlevel = problemlevel;
	}

	public String getProblemdetail() {
		return this.problemdetail;
	}

	public void setProblemdetail(String problemdetail) {
		this.problemdetail = problemdetail;
	}

	public String getProblemindex() {
		return this.problemindex;
	}

	public void setProblemindex(String problemindex) {
		this.problemindex = problemindex;
	}

	public Integer getProblemcisactive() {
		return this.problemcisactive;
	}

	public void setProblemcisactive(Integer problemcisactive) {
		this.problemcisactive = problemcisactive;
	}

	public String getProblemanswerstring() {
		return this.problemanswerstring;
	}

	public void setProblemanswerstring(String problemanswerstring) {
		this.problemanswerstring = problemanswerstring;
	}

	public String getProblemanswerdetail() {
		return this.problemanswerdetail;
	}

	public void setProblemanswerdetail(String problemanswerdetail) {
		this.problemanswerdetail = problemanswerdetail;
	}

}
