package dbmodel;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Sourcechapter generated by hbm2java
 */
@Entity
@Table(name = "sourcechapter")
public class SourceChapter {

	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private Integer idsourcechapter;
	private Integer sourceid;
	public Integer getSourceid() {
		return sourceid;
	}

	public void setSourceid(Integer sourceid) {
		this.sourceid = sourceid;
	}

	private String sourcechaptername;
	private Integer sourcechapterindex;
	

	public SourceChapter() {
	}

	public SourceChapter(Integer sourceid, String sourcechaptername, Integer sourcechapterindex) {
		this.sourceid = sourceid;
		this.sourcechaptername = sourcechaptername;
		this.sourcechapterindex = sourcechapterindex;
		//this.problems = problems;
	}

	public Integer getIdsourcechapter() {
		return this.idsourcechapter;
	}

	public void setIdsourcechapter(Integer idsourcechapter) {
		this.idsourcechapter = idsourcechapter;
	}
	
	public String getSourcechaptername() {
		return this.sourcechaptername;
	}

	public void setSourcechaptername(String sourcechaptername) {
		this.sourcechaptername = sourcechaptername;
	}

	public Integer getSourcechapterindex() {
		return this.sourcechapterindex;
	}

	public void setSourcechapterindex(Integer sourcechapterindex) {
		this.sourcechapterindex = sourcechapterindex;
	}

}
