package dbmodel;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Source generated by hbm2java
 */
@Entity
@Table(name = "source")
public class Source implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Integer idsource;

    private String sourcename;
    private Integer sourcetype;

    @Column(name="idstage")
    private Integer idStage;

    public Source() {
    }

    public Source(String sourcename, Integer sourcetype) {
        this.sourcename = sourcename;
        this.sourcetype = sourcetype;
    }

    public Integer getIdsource() {
        return this.idsource;
    }

    public void setIdsource(Integer idsource) {
        this.idsource = idsource;
    }

    public String getSourcename() {
        return this.sourcename;
    }

    public void setSourcename(String sourcename) {
        this.sourcename = sourcename;
    }

    public Integer getSourcetype() {
        return this.sourcetype;
    }

    public void setSourcetype(Integer sourcetype) {
        this.sourcetype = sourcetype;
    }

    public Integer getIdStage() {
        return idStage;
    }

    public void setIdStage(Integer idStage) {
        this.idStage = idStage;
    }
}
