package dbmodel;
// default package
// Generated May 27, 2018 11:48:26 AM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.*;
import java.util.Date;

/**
 * Work generated by hbm2java
 */
@Entity
@Table(name = "work")
public class Work implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Integer idwork;
	private Integer idproblem;

	public Integer getIdproblem() {
		return idproblem;
	}

	public void setIdproblem(Integer idproblem) {
		this.idproblem = idproblem;
	}

	private Date workdate;
	private Integer usedtime;
	private String workdetail;
	private Integer workmark;
	private Integer reason;

	Integer    idstarreason;

	public Integer getIdstarreason() {
		return idstarreason;
	}

	public void setIdstarreason(Integer idstarreason) {
		this.idstarreason = idstarreason;
	}

	public enum WorkColumnName {idproblem,usedtime,workdetail,workdate,paperid};
	
	public Work() {
	}

	public Work(Integer idproblem, Date workdate, Integer usedtime, String workdetail, Integer workmark, Integer reason) {
		this.idproblem = idproblem;
		this.workdate = workdate;
		this.usedtime = usedtime;
		this.workdetail = workdetail;
		this.workmark = workmark;
		this.reason = reason;
	}

	public Integer getIdwork() {
		return this.idwork;
	}

	public void setIdwork(Integer idwork) {
		this.idwork = idwork;
	}

	public Date getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(Date workdate) {
		this.workdate = workdate;
	}

	public Integer getUsedtime() {
		return this.usedtime;
	}

	public void setUsedtime(Integer usedtime) {
		this.usedtime = usedtime;
	}

	public String getWorkdetail() {
		return this.workdetail;
	}

	public void setWorkdetail(String workdetail) {
		this.workdetail = workdetail;
	}

	public Integer getWorkmark() {
		return this.workmark;
	}

	public void setWorkmark(Integer workmark) {
		this.workmark = workmark;
	}

	public Integer getReason() {
		return this.reason;
	}

	public void setReason(Integer reason) {
		this.reason = reason;
	}

}
